# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build
  jobs:
  - job: BuildDoc
    displayName: Build documentation
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'

    - script: pip install --upgrade pip
      displayName: 'Upgrade PIP'

    - script: pip install mkdocs
      displayName: 'Install mkdocs'

    - script: |
        cd s
        python -m mkdocs build
      displayName: 'Build documentation'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/site'
        artifact: 'site'
        publishLocation: 'pipeline'
      displayName: 'Publish site as artifact'

- stage: Publish
  pool:
    vmImage: 'windows-latest'
  displayName: Publish to KayTrust Developer
  jobs:
  - job: Upload
    displayName: Upload to Azure Blob Storage
    steps:
    - task: AzureFileCopy@4
      displayName: Copy files to container on Azure
      inputs:
        SourcePath: '$(System.ArtifactsDirectory)/site'
        azureSubscription: 'Everis Peru SAC(f6205eb2-ffec-4f83-bad1-b1454cfd198d)'
        Destination: 'AzureBlob'
        storage: 'kaytrust'
        ContainerName: 'developer'
        BlobPrefix: 'doc'
