# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: SwaggerUiGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: FelixGitHub
    name: swagger-api/swagger-ui
    ref: master


trigger:
- none

stages:

- stage: Build_Swagger
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build swagger documentation
  jobs:
  - job: BuildSwaggerDoc
    displayName: Build documentation using MkDocs
    steps:

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/swagger'
        artifact: 'swagger'
        publishLocation: 'pipeline'
      displayName: 'Publish doc as artifact'

- stage: Publish_SwaggerApi
  dependsOn: Build_Swagger
  pool:
    vmImage: 'windows-latest'
  displayName: Publish swagger-openapi.yaml to a blob block
  jobs:
  - deployment: Upload
    displayName: Upload to Azure Blob Storage
    environment: KT-Swagger-Docs
    variables:
      AZURE_STORAGE_ACCOUNT: 'ktswagger'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Clear Azure Swagger container'
            inputs:
              azureSubscription: 'KayTrust(c6b6dad0-020f-449d-9640-e67084c77750)'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob delete-batch -s docs --account-name $(AZURE_STORAGE_ACCOUNT) --auth-mode login'
          - task: AzureFileCopy@4
            displayName: Copy site files to container on Azure
            inputs:
              SourcePath: '$(Pipeline.Workspace)/swagger/*'
              azureSubscription: 'KayTrust(c6b6dad0-020f-449d-9640-e67084c77750)'
              Destination: 'AzureBlob'
              storage: '$(AZURE_STORAGE_ACCOUNT)'
              ContainerName: docs

##############################################

- stage: Build_React_SwaggerUI
