# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build static documentation
  jobs:
  - job: BuildDoc
    displayName: Build documentation using MkDocs
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'

    - script: pip install --upgrade pip
      displayName: 'Upgrade PIP'

    - script: pip install mkdocs
      displayName: 'Install mkdocs'

    - script: |
        cd s
        python -m mkdocs build
      displayName: 'Build site'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/site'
        artifact: 'site'
        publishLocation: 'pipeline'
      displayName: 'Publish site as artifact'

- stage: Publish
  pool:
    vmImage: 'windows-latest'
  displayName: Publish to KayTrust Developer
  jobs:
  - deployment: Upload
    displayName: Upload to Azure Blob Storage
    environment: 'Developer website prod'
    variables:
      AZURE_STORAGE_ACCOUNT: 'kaytrust'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'site'
              targetPath: '$(Pipeline.Workspace)/site'
            displayName: Download site as artifact
          - task: AzureCLI@2
            displayName: 'Clear Azure container'
            inputs:
              azureSubscription: 'Everis Peru SAC(f6205eb2-ffec-4f83-bad1-b1454cfd198d)'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob delete-batch -s `$web --account-name $(AZURE_STORAGE_ACCOUNT) --auth-mode login'
          - task: AzureFileCopy@4
            displayName: Copy site files to container on Azure
            inputs:
              SourcePath: '$(Pipeline.Workspace)/site/*'
              azureSubscription: 'Everis Peru SAC(f6205eb2-ffec-4f83-bad1-b1454cfd198d)'
              Destination: 'AzureBlob'
              storage: '$(AZURE_STORAGE_ACCOUNT)'
              ContainerName: '$web'