site_name: KayTrust Developer Documentation
theme:
  font:
    text: Lato
  icon:
    logo: material/code-tags-check
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.instant
nav:
    - Home: index.md
    - Specs: Specs.md
    - Manuals: Manuals.md
    - Tutorials: Tutorials.md
#    - Products: products.md
#    - Join: join.md
#    - Download: download.md
#    - About: about.md
