site_name: KayTrust Developer Documentation
theme: flatly
nav:
    - Home: index.md
    - Specs: Specs.md
    - Manuals: Manuals.md
    - Tutorials: Tutorials.md
#    - Products: products.md
#    - Join: join.md
#    - Download: download.md
#    - About: about.md
